use crate::analytics::{CashFlowBreakdown, CashFlowSegment, CashFlowSegmentKind, MonthSummary};
use crate::i18n::{format as trf, gettext};
use crate::model::MonthKey;
use adw::glib::prelude::IsA;
use adw::gtk;
use adw::gtk::prelude::*;
use adw::prelude::*;
use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;
use std::cell::{Cell, RefCell};
use std::rc::Rc;

mod basic;
mod builder;
mod buttons;
mod cards;
mod chart;
mod dialogs;
mod forms;
mod progress;
mod search;
mod style;

pub use basic::*;
pub use builder::*;
pub use buttons::*;
pub use cards::*;
pub use chart::*;
pub use dialogs::*;
pub use forms::*;
pub use progress::*;
pub use search::*;
pub use style::*;
