use super::super::*;
use super::loading::{schedule_management_forms_load, ManagementFormsLoad};
use super::render::{
    set_management_form_action_widgets_sensitive, set_management_menu_actions_enabled,
};

pub(super) struct ManagementDialogSetup<'a> {
    pub(super) window: &'a adw::ApplicationWindow,
    pub(super) management_dialog: &'a adw::Dialog,
    pub(super) add_button: &'a gtk::Button,
    pub(super) add_rule_row: &'a adw::ActionRow,
    pub(super) add_budget_row: &'a adw::ActionRow,
    pub(super) add_alias_row: &'a adw::ActionRow,
    pub(super) group_rules_action: &'a gtk::gio::SimpleAction,
    pub(super) combine_rules_action: &'a gtk::gio::SimpleAction,
    pub(super) clean_orphaned_rules_action: &'a gtk::gio::SimpleAction,
    pub(super) move_budget_code_action: &'a gtk::gio::SimpleAction,
    pub(super) use_real_income_action: &'a gtk::gio::SimpleAction,
    pub(super) use_planned_income_action: &'a gtk::gio::SimpleAction,
    pub(super) use_monthly_values_action: &'a gtk::gio::SimpleAction,
    pub(super) use_yearly_values_action: &'a gtk::gio::SimpleAction,
    pub(super) back_up_configuration_action: &'a gtk::gio::SimpleAction,
    pub(super) restore_latest_backup_action: &'a gtk::gio::SimpleAction,
    pub(super) rule_bulk_menu_button: &'a gtk::MenuButton,
    pub(super) budget_bulk_menu_button: &'a gtk::MenuButton,
    pub(super) save_button: &'a gtk::Button,
    pub(super) page_actions_button: &'a gtk::MenuButton,
    pub(super) stack: &'a adw::ViewStack,
    pub(super) filter_entry: &'a gtk::SearchEntry,
    pub(super) filter_search_bar: &'a gtk::SearchBar,
    pub(super) rules_list: gtk::Box,
    pub(super) rules_forms: Rc<RefCell<Vec<RuleForm>>>,
    pub(super) rules_scroll: &'a gtk::ScrolledWindow,
    pub(super) budgets_list: gtk::Box,
    pub(super) budgets_forms: Rc<RefCell<Vec<BudgetForm>>>,
    pub(super) budgets_scroll: &'a gtk::ScrolledWindow,
    pub(super) aliases_list: gtk::Box,
    pub(super) aliases_forms: Rc<RefCell<Vec<AliasForm>>>,
    pub(super) aliases_scroll: &'a gtk::ScrolledWindow,
    pub(super) status: gtk::Label,
    pub(super) dialog_closed: Rc<Cell<bool>>,
    pub(super) save_running: Rc<Cell<bool>>,
    pub(super) finish_management_dialog: Rc<dyn Fn()>,
    pub(super) initial_filter: Option<&'a str>,
    pub(super) advanced_features: bool,
    pub(super) state: &'a Rc<RefCell<AppData>>,
    pub(super) ui_handles: &'a Rc<UiHandles>,
    pub(super) status_handle: StatusHandle,
}

pub(super) fn finish_management_dialog_setup(setup: ManagementDialogSetup<'_>) {
    let ManagementDialogSetup {
        window,
        management_dialog,
        add_button,
        add_rule_row,
        add_budget_row,
        add_alias_row,
        group_rules_action,
        combine_rules_action,
        clean_orphaned_rules_action,
        move_budget_code_action,
        use_real_income_action,
        use_planned_income_action,
        use_monthly_values_action,
        use_yearly_values_action,
        back_up_configuration_action,
        restore_latest_backup_action,
        rule_bulk_menu_button,
        budget_bulk_menu_button,
        save_button,
        page_actions_button,
        stack,
        filter_entry,
        filter_search_bar,
        rules_list,
        rules_forms,
        rules_scroll,
        budgets_list,
        budgets_forms,
        budgets_scroll,
        aliases_list,
        aliases_forms,
        aliases_scroll,
        status,
        dialog_closed,
        save_running,
        finish_management_dialog,
        initial_filter,
        advanced_features,
        state,
        ui_handles,
        status_handle,
    } = setup;
    connect_management_dialog_actions(ManagementDialogActions {
        management_dialog,
        add_button,
        add_rule_row,
        add_budget_row,
        add_alias_row,
        group_rules_action,
        combine_rules_action,
        clean_orphaned_rules_action,
        move_budget_code_action,
        use_real_income_action,
        use_planned_income_action,
        use_monthly_values_action,
        use_yearly_values_action,
        back_up_configuration_action,
        restore_latest_backup_action,
        save_button,
        page_actions_button,
        stack,
        filter_entry,
        filter_search_bar,
        rules_list: &rules_list,
        rules_forms: &rules_forms,
        rules_scroll,
        budgets_list: &budgets_list,
        budgets_forms: &budgets_forms,
        budgets_scroll,
        aliases_list: &aliases_list,
        aliases_forms: &aliases_forms,
        aliases_scroll,
        status: &status,
        dialog_closed: Rc::clone(&dialog_closed),
        save_running: Rc::clone(&save_running),
        finish_management_dialog: Rc::clone(&finish_management_dialog),
        state,
        ui_handles,
    });
    let management_form_action_widgets = vec![
        add_button.clone().upcast::<gtk::Widget>(),
        add_rule_row.clone().upcast::<gtk::Widget>(),
        add_budget_row.clone().upcast::<gtk::Widget>(),
        add_alias_row.clone().upcast::<gtk::Widget>(),
        rule_bulk_menu_button.clone().upcast::<gtk::Widget>(),
        budget_bulk_menu_button.clone().upcast::<gtk::Widget>(),
        save_button.clone().upcast::<gtk::Widget>(),
    ];
    let management_menu_actions = vec![
        group_rules_action.clone(),
        combine_rules_action.clone(),
        clean_orphaned_rules_action.clone(),
        move_budget_code_action.clone(),
        use_real_income_action.clone(),
        use_planned_income_action.clone(),
        use_monthly_values_action.clone(),
        use_yearly_values_action.clone(),
    ];
    set_management_form_action_widgets_sensitive(&management_form_action_widgets, false);
    set_management_menu_actions_enabled(&management_menu_actions, false);
    page_actions_button.set_sensitive(false);
    if let Some(filter) = initial_filter {
        filter_search_bar.set_search_mode(true);
        filter_entry.set_text(filter);
    }
    management_dialog.present(Some(window));
    schedule_management_forms_load(ManagementFormsLoad {
        advanced_features,
        rules_list,
        rules_forms,
        budgets_list,
        budgets_forms,
        aliases_list,
        aliases_forms,
        filter_entry: filter_entry.clone(),
        status,
        dialog_closed,
        advanced_autofill: Rc::clone(&ui_handles.advanced_autofill),
        ui_handles: Rc::clone(ui_handles),
        action_widgets: management_form_action_widgets,
        menu_actions: management_menu_actions,
        page_actions_button: page_actions_button.clone(),
        status_handle,
    });
}
