#[cfg(feature = "local-ai")]
use super::categories::{category_guess, clean_label, CategoryGuess};
#[cfg(feature = "local-ai")]
use super::LocalAiRecord;
use super::{LocalAiDraft, LocalAiError, LocalAiInput, LocalAiModelSource, LocalAiPatternHint};
#[cfg(feature = "local-ai")]
use crate::data::{EditableBudget, EditableRule};
#[cfg(feature = "local-ai")]
use crate::util::normalize_key;
#[cfg(feature = "local-ai")]
use std::collections::BTreeSet;
#[cfg(feature = "local-ai")]
use std::path::Path;

#[cfg(feature = "local-ai")]
const MIN_RECORD_COUNT: usize = 2;
#[cfg(feature = "local-ai")]
const MAX_DRAFT_RECORDS: usize = 24;
#[cfg(feature = "local-ai")]
const MAX_PATTERN_HINTS: usize = 48;
#[cfg(feature = "local-ai")]
const BASE_PRIORITY: i32 = 180;
#[cfg(feature = "local-ai")]
const ADAPTER_NOTE: &str = "Generated by the bundled local AI adapter.";
#[cfg(feature = "local-ai")]
const PATTERN_REASON: &str = "Repeated local transaction pattern.";

#[cfg(feature = "local-ai")]
pub(super) fn runtime_generate_configuration_draft(
    input: &LocalAiInput,
    source: Option<&LocalAiModelSource>,
) -> std::result::Result<Option<LocalAiDraft>, LocalAiError> {
    if let Some(source) = source {
        validate_runtime_assets(source.path())?;
    }

    let draft = DraftBuilder::from_input(input).finish();
    Ok((!draft_is_empty(&draft)).then_some(draft))
}

#[cfg(not(feature = "local-ai"))]
pub(super) fn runtime_generate_configuration_draft(
    _input: &LocalAiInput,
    _source: Option<&LocalAiModelSource>,
) -> std::result::Result<Option<LocalAiDraft>, LocalAiError> {
    Ok(None)
}

#[cfg(feature = "local-ai")]
pub(super) fn runtime_pattern_hints(
    input: &LocalAiInput,
    source: Option<&LocalAiModelSource>,
) -> std::result::Result<Vec<LocalAiPatternHint>, LocalAiError> {
    if let Some(source) = source {
        validate_runtime_assets(source.path())?;
    }

    Ok(pattern_hints(input))
}

#[cfg(not(feature = "local-ai"))]
pub(super) fn runtime_pattern_hints(
    _input: &LocalAiInput,
    _source: Option<&LocalAiModelSource>,
) -> std::result::Result<Vec<LocalAiPatternHint>, LocalAiError> {
    Ok(Vec::new())
}

#[cfg(feature = "local-ai")]
fn validate_runtime_assets(model_dir: &Path) -> std::result::Result<(), LocalAiError> {
    let tokenizer_path = model_dir.join("tokenizer.json");
    let tokenizer = tokenizers::Tokenizer::from_file(&tokenizer_path).map_err(|error| {
        local_ai_error(format!(
            "Could not load local AI tokenizer {}: {error}",
            tokenizer_path.display()
        ))
    })?;
    if tokenizer.get_vocab_size(false) == 0 {
        return Err(local_ai_error("Local AI tokenizer has an empty vocabulary"));
    }

    let _ = std::any::type_name::<candle_core::Device>();
    let _ = tract_onnx::onnx();
    Ok(())
}

#[cfg(feature = "local-ai")]
fn pattern_hints(input: &LocalAiInput) -> Vec<LocalAiPatternHint> {
    draft_records(input)
        .into_iter()
        .filter_map(|record| {
            let category = category_guess(record);
            Some(LocalAiPatternHint {
                label: search_text(record)?,
                category: category.category,
                budget_code: category.budget_code,
                reason: PATTERN_REASON.to_string(),
            })
        })
        .take(MAX_PATTERN_HINTS)
        .collect()
}

#[cfg(feature = "local-ai")]
#[derive(Default)]
struct DraftBuilder {
    budget_codes: BTreeSet<String>,
    rule_keys: BTreeSet<(String, String, String, String)>,
    budgets: Vec<EditableBudget>,
    rules: Vec<EditableRule>,
}

#[cfg(feature = "local-ai")]
impl DraftBuilder {
    fn from_input(input: &LocalAiInput) -> Self {
        let mut builder = Self::default();
        for record in draft_records(input).into_iter().take(MAX_DRAFT_RECORDS) {
            builder.push_record(record);
        }
        builder
    }

    fn push_record(&mut self, record: &LocalAiRecord) {
        let Some(search) = search_text(record) else {
            return;
        };
        let category = category_guess(record);
        self.push_budget(&category, record_direction(record));
        self.push_rule(record, &search, &category);
    }

    fn push_budget(&mut self, category: &CategoryGuess, direction: &str) {
        if !self
            .budget_codes
            .insert(normalize_key(&category.budget_code))
        {
            return;
        }

        self.budgets.push(EditableBudget {
            code: category.budget_code.clone(),
            category: category.category.clone(),
            monthly_budget: "0".to_string(),
            yearly_budget: String::new(),
            direction: direction.to_string(),
            income_basis: "real".to_string(),
            notes: ADAPTER_NOTE.to_string(),
        });
    }

    fn push_rule(&mut self, record: &LocalAiRecord, search: &str, category: &CategoryGuess) {
        let direction = record_direction(record).to_string();
        let key = (
            "any".to_string(),
            normalize_key(search),
            normalize_key(&category.budget_code),
            normalize_key(&direction),
        );
        if !self.rule_keys.insert(key) {
            return;
        }

        self.rules.push(EditableRule {
            priority: BASE_PRIORITY.saturating_sub(self.rules.len() as i32),
            active: true,
            field: "any".to_string(),
            search: search.to_string(),
            is_regex: false,
            category: category.category.clone(),
            budget_code: category.budget_code.clone(),
            direction,
            amount_min: String::new(),
            amount_max: String::new(),
            notes: ADAPTER_NOTE.to_string(),
        });
    }

    fn finish(self) -> LocalAiDraft {
        LocalAiDraft {
            budgets: self.budgets,
            rules: self.rules,
            aliases: Vec::new(),
            ignored_patterns: Vec::new(),
            pattern_hints: Vec::new(),
        }
    }
}

#[cfg(feature = "local-ai")]
fn draft_records(input: &LocalAiInput) -> Vec<&LocalAiRecord> {
    let mut records = input
        .records
        .iter()
        .filter(|record| useful_record(record))
        .collect::<Vec<_>>();
    records.sort_by(|left, right| {
        right
            .count
            .cmp(&left.count)
            .then_with(|| normalize_key(&left.label).cmp(&normalize_key(&right.label)))
    });
    records
}

#[cfg(feature = "local-ai")]
fn useful_record(record: &LocalAiRecord) -> bool {
    record.count >= MIN_RECORD_COUNT
        && !record.label.trim().is_empty()
        && matches!(
            normalize_key(&record.direction).as_str(),
            "expense" | "income"
        )
}

#[cfg(feature = "local-ai")]
fn search_text(record: &LocalAiRecord) -> Option<String> {
    let search = clean_label(&record.label);
    (!search.is_empty()).then_some(search)
}

#[cfg(feature = "local-ai")]
fn record_direction(record: &LocalAiRecord) -> &'static str {
    match normalize_key(&record.direction).as_str() {
        "income" => "income",
        _ => "expense",
    }
}

#[cfg(feature = "local-ai")]
fn draft_is_empty(draft: &LocalAiDraft) -> bool {
    draft.budgets.is_empty()
        && draft.rules.is_empty()
        && draft.aliases.is_empty()
        && draft.ignored_patterns.is_empty()
}

#[cfg(feature = "local-ai")]
fn local_ai_error(message: impl Into<String>) -> LocalAiError {
    LocalAiError {
        message: message.into(),
    }
}

#[cfg(all(test, feature = "local-ai"))]
mod tests {
    use super::*;

    #[test]
    fn draft_uses_category_table_for_repeated_records() {
        let input = LocalAiInput {
            locale: "en".to_string(),
            records: vec![record("Jumbo Supermarkt", "expense", 3, "", "")],
        };

        let draft = runtime_generate_configuration_draft(&input, None)
            .expect("runtime should not fail")
            .expect("repeated record should produce a draft");

        assert_eq!(draft.budgets[0].code, "FOOD");
        assert_eq!(draft.rules[0].budget_code, "FOOD");
        assert_eq!(draft.rules[0].search, "Jumbo Supermarkt");
    }

    #[test]
    fn pattern_hints_prefer_existing_category() {
        let input = LocalAiInput {
            locale: "en".to_string(),
            records: vec![record("Pet Store", "expense", 2, "Pets", "PET")],
        };

        let hints = runtime_pattern_hints(&input, None).expect("runtime should not fail");

        assert_eq!(hints[0].category, "Pets");
        assert_eq!(hints[0].budget_code, "PET");
    }

    fn record(
        label: &str,
        direction: &str,
        count: usize,
        existing_category: &str,
        existing_budget_code: &str,
    ) -> LocalAiRecord {
        LocalAiRecord {
            label: label.to_string(),
            descriptions: Vec::new(),
            tags: Vec::new(),
            direction: direction.to_string(),
            existing_category: existing_category.to_string(),
            existing_budget_code: existing_budget_code.to_string(),
            count,
        }
    }
}
